class TestCliE2E:
    def test_ingest_command_calls_run_pipeline(self, monkeypatch) -> None: ...
    def test_ingest_records_command_calls_ingest_source_reports(
        self, monkeypatch
    ) -> None: ...
    def test_search_news_command_calls_search_news(self, monkeypatch) -> None: ...
    def test_generate_logs_command_calls_generate_logs(self, monkeypatch) -> None: ...
    def test_report_command_emits_markdown_brief(self) -> None: ...
    def test_no_reclassify_command_exists(self) -> None: ...
    def test_no_redigest_command_exists(self) -> None: ...
