from collections.abc import Callable
from datetime import datetime
from typing import Any

from disaster_report.ai.base import FilterResult, SummaryResult
from disaster_report.models import IncidentLog, NewsItem, SourceReport
from disaster_report.store.base import Warehouse

class TestIngestSourceReports:
    def test_ingest_stores_all_fetched_reports_unconditionally(self) -> None: ...
    def test_ingest_source_reports_counts_all_stored(self) -> None: ...
    def test_re_ingest_source_reports_is_no_churn(self) -> None: ...
    def test_ingest_source_reports_makes_no_ddg_no_ai_calls(self) -> None: ...
    def test_ingest_stores_report_places(self) -> None: ...
    def test_ingest_is_fail_isolated_per_source(self) -> None: ...

class TestSearchNews:
    def test_search_news_bare_stores_report_with_no_candidate_news(self) -> None: ...
    def test_search_news_calls_digester_filter_for_candidate_news(self) -> None: ...
    def test_search_news_does_not_call_digester_summarize(self) -> None: ...
    def test_search_news_writes_no_incident_logs(self) -> None: ...
    def test_search_news_ai_not_called_when_no_candidate_news(self) -> None: ...
    def test_shared_news_joins_reports_into_one_incident(self) -> None: ...
    def test_search_news_births_incident_for_new_news(self) -> None: ...
    def test_search_news_joins_existing_incident_for_known_news(self) -> None: ...
    def test_search_news_marks_report_searched(self) -> None: ...
    def test_search_news_skips_already_searched_report(self) -> None: ...
    def test_unmonitored_report_has_no_news_search(self) -> None: ...
    def test_source_id_bypasses_should_monitor(self) -> None: ...
    def test_source_id_does_not_affect_other_reports(self) -> None: ...
    def test_search_news_strict_first_loose_only_when_strict_empty(self) -> None: ...
    def test_search_news_skips_loose_when_strict_returns_results(self) -> None: ...
    def test_search_news_skips_search_when_both_keys_empty(self) -> None: ...
    def test_search_news_passes_news_timelimit_to_ddg(self) -> None: ...
    def test_search_news_defaults_news_timelimit_to_one_week(self) -> None: ...
    def test_re_ingested_news_keeps_original_published_date(self) -> None: ...
    def test_active_incident_is_repolled_on_second_run(self) -> None: ...
    def test_dormant_incident_not_repolled(self) -> None: ...
    def test_repoll_is_per_incident_not_per_report(self) -> None: ...
    def test_repoll_no_churn_when_no_new_news(self) -> None: ...

class TestGenerateLogs:
    def test_generate_logs_appends_timeline_when_genuinely_new_news(self) -> None: ...
    def test_generate_logs_no_churn_when_all_news_already_logged(self) -> None: ...
    def test_generate_logs_calls_digester_summarize_not_filter(self) -> None: ...
    def test_generate_logs_passes_prior_summaries_to_summarize(self) -> None: ...
    def test_log_datetime_uses_max_published_date_of_batch(self) -> None: ...
    def test_generate_logs_batches_one_timeline_row_per_incident(self) -> None: ...
    def test_generate_logs_reads_news_committed_by_search_news(self) -> None: ...
    def test_generate_logs_fetches_only_unsummarized_news(self) -> None: ...
    def test_generate_logs_writes_provenance_junction(self) -> None: ...
    def test_generate_logs_no_churn_when_all_news_summarized(self) -> None: ...
    def test_generate_logs_handles_late_arriving_news(self) -> None: ...
    def test_generate_logs_atomic_log_and_provenance(self) -> None: ...
    def test_generate_logs_log_datetime_fallback_on_pk_collision(self) -> None: ...
    def test_generate_logs_skips_below_threshold(self) -> None: ...

class TestRunPipeline:
    def test_run_pipeline_runs_all_three_phases_in_order(self) -> None: ...
    def test_run_pipeline_returns_summed_ingest_report(self) -> None: ...
    def test_run_pipeline_continues_to_phase_three_after_partial_phase_two(
        self,
    ) -> None: ...

class _FakeAdapter:
    def __init__(self, reports: list[SourceReport]) -> None: ...
    def fetch(self) -> list[SourceReport]: ...
    def should_monitor(self, report: SourceReport) -> bool: ...
    def derive_keys(self, report: SourceReport) -> tuple[str, str]: ...

class _BrokenAdapter:
    def fetch(self) -> list[SourceReport]: ...
    def should_monitor(self, report: SourceReport) -> bool: ...
    def derive_keys(self, report: SourceReport) -> tuple[str, str]: ...

class _FakeDDG:
    def __init__(self, news: tuple[NewsItem, ...]) -> None: ...
    last_timelimit: str | None
    queries: list[str]
    def search(self, query: str, timelimit: str | None = None) -> list[NewsItem]: ...

class _KeyedAdapter:
    def __init__(self, strict: str, loose: str) -> None: ...
    def fetch(self) -> list[SourceReport]: ...
    def should_monitor(self, report: SourceReport) -> bool: ...
    def derive_keys(self, report: SourceReport) -> tuple[str, str]: ...

class _GatedAdapter:
    def __init__(self, monitor: bool) -> None: ...
    def fetch(self) -> list[SourceReport]: ...
    def should_monitor(self, report: SourceReport) -> bool: ...
    def derive_keys(self, report: SourceReport) -> tuple[str, str]: ...

class _FakeDigester:
    def filter(
        self,
        candidate_news: list[NewsItem],
        *,
        incident_type: str,
        incident_name: str,
        incident_places: list,
        incident_date: str,
    ) -> FilterResult: ...
    def summarize(
        self,
        selected_news: list[NewsItem],
        prior_summaries: list[IncidentLog],
        *,
        incident_type: str,
        incident_name: str,
        incident_places: list,
        incident_date: str,
    ) -> SummaryResult: ...

class _PriorCapturingDigester:
    def __init__(self) -> None: ...
    captured_priors: list[list[IncidentLog]]
    def filter(
        self,
        candidate_news: list[NewsItem],
        *,
        incident_type: str,
        incident_name: str,
        incident_places: list,
        incident_date: str,
    ) -> FilterResult: ...
    def summarize(
        self,
        selected_news: list[NewsItem],
        prior_summaries: list[IncidentLog],
        *,
        incident_type: str,
        incident_name: str,
        incident_places: list,
        incident_date: str,
    ) -> SummaryResult: ...

class _NewsCapturingDigester:
    def __init__(self) -> None: ...
    captured_news: list[list[NewsItem]]
    summarize_calls: int
    def filter(
        self,
        candidate_news: list[NewsItem],
        *,
        incident_type: str,
        incident_name: str,
        incident_places: list,
        incident_date: str,
    ) -> FilterResult: ...
    def summarize(
        self,
        selected_news: list[NewsItem],
        prior_summaries: list[IncidentLog],
        *,
        incident_type: str,
        incident_name: str,
        incident_places: list,
        incident_date: str,
    ) -> SummaryResult: ...

def _built_run(
    news_results: tuple[NewsItem, ...] | None = ...,
    clock: Callable[[], datetime] | None = ...,
    broken_source: str | None = ...,
    warehouse: Warehouse | None = ...,
    digester: Any | None = ...,
) -> tuple[list[object], Warehouse, _FakeDDG, Any, Callable[[], datetime]]: ...
def _adapters(broken_source: str | None) -> list[object]: ...
def _warehouse() -> Warehouse: ...
def _ddg(news_results: tuple[NewsItem, ...] | None) -> _FakeDDG: ...
def _digester() -> _FakeDigester: ...
def _clock(clock: Callable[[], datetime] | None) -> Callable[[], datetime]: ...
def _some_news(published_date: str = ...) -> tuple[NewsItem, ...]: ...
def _shared_news() -> tuple[NewsItem, ...]: ...
def _late_news() -> tuple[NewsItem, ...]: ...
def _source_report(
    source: str,
    source_id: str,
    incident_type: str,
    name: str,
) -> SourceReport: ...
