
from __future__ import annotations

_SUBREGION_COUNTRIES: dict[str, tuple[str, ...]] = {
    "Eastern Africa": (
        "BI",
        "KM",
        "DJ",
        "ER",
        "ET",
        "KE",
        "MG",
        "MW",
        "MU",
        "MZ",
        "RE",
        "RW",
        "SC",
        "SO",
        "SS",
        "TZ",
        "UG",
        "YT",
        "ZM",
        "ZW",
    ),
    "Middle Africa": (
        "AO",
        "CD",
        "CF",
        "CG",
        "CM",
        "GA",
        "GQ",
        "ST",
        "TD",
    ),
    "Northern Africa": (
        "DZ",
        "EG",
        "EH",
        "LY",
        "MA",
        "SD",
        "TN",
    ),
    "Southern Africa": (
        "BW",
        "LS",
        "NA",
        "SZ",
        "ZA",
    ),
    "Western Africa": (
        "BF",
        "BJ",
        "CI",
        "CV",
        "GH",
        "GM",
        "GN",
        "GW",
        "LR",
        "ML",
        "MR",
        "NE",
        "NG",
        "SH",
        "SL",
        "SN",
        "TG",
    ),
    "Caribbean": (
        "AG",
        "AI",
        "AW",
        "BB",
        "BL",
        "BQ",
        "BS",
        "CU",
        "CW",
        "DM",
        "DO",
        "GD",
        "GP",
        "HT",
        "JM",
        "KN",
        "KY",
        "LC",
        "MF",
        "MQ",
        "MS",
        "PR",
        "SX",
        "TC",
        "TT",
        "VC",
        "VG",
        "VI",
    ),
    "Central America": (
        "BZ",
        "CR",
        "GT",
        "HN",
        "MX",
        "NI",
        "PA",
        "SV",
    ),
    "Northern America": (
        "BM",
        "CA",
        "GL",
        "PM",
        "US",
    ),
    "South America": (
        "AR",
        "BO",
        "BR",
        "CL",
        "CO",
        "EC",
        "FK",
        "GF",
        "GY",
        "PE",
        "PY",
        "SR",
        "UY",
        "VE",
    ),
    "Central Asia": (
        "KG",
        "KZ",
        "TJ",
        "TM",
        "UZ",
    ),
    "Eastern Asia": (
        "CN",
        "HK",
        "JP",
        "KP",
        "KR",
        "MO",
        "MN",
        "TW",
    ),
    "South-Eastern Asia": (
        "BN",
        "ID",
        "KH",
        "LA",
        "MM",
        "MY",
        "PH",
        "SG",
        "TH",
        "TL",
        "VN",
    ),
    "Southern Asia": (
        "AF",
        "BD",
        "BT",
        "IN",
        "IR",
        "LK",
        "MV",
        "NP",
        "PK",
    ),
    "Western Asia": (
        "AE",
        "AM",
        "AZ",
        "BH",
        "CY",
        "GE",
        "IL",
        "IQ",
        "JO",
        "KW",
        "LB",
        "OM",
        "PS",
        "QA",
        "SA",
        "SY",
        "TR",
        "YE",
    ),
    "Eastern Europe": (
        "BG",
        "BY",
        "CZ",
        "HU",
        "MD",
        "PL",
        "RO",
        "RU",
        "SK",
        "UA",
    ),
    "Northern Europe": (
        "AX",
        "DK",
        "EE",
        "FI",
        "FO",
        "GB",
        "GG",
        "IE",
        "IM",
        "IS",
        "JE",
        "LV",
        "LT",
        "NO",
        "SJ",
        "SE",
    ),
    "Southern Europe": (
        "AD",
        "AL",
        "BA",
        "ES",
        "GI",
        "GR",
        "HR",
        "IT",
        "ME",
        "MK",
        "MT",
        "PT",
        "RS",
        "SM",
        "SI",
        "VA",
    ),
    "Western Europe": (
        "AT",
        "BE",
        "CH",
        "DE",
        "FR",
        "LI",
        "LU",
        "MC",
        "NL",
    ),
    "Australia and New Zealand": (
        "AU",
        "NF",
        "NZ",
    ),
    "Melanesia": (
        "FJ",
        "NC",
        "PG",
        "SB",
        "VU",
    ),
    "Micronesia": (
        "FM",
        "GU",
        "KI",
        "MH",
        "MP",
        "NR",
        "PW",
    ),
    "Polynesia": (
        "AS",
        "CK",
        "NU",
        "PF",
        "PN",
        "TK",
        "TO",
        "TV",
        "WF",
        "WS",
    ),
}

_SUBREGIONS_BY_ALPHA_2: dict[str, str] = {
    code: subregion
    for subregion, codes in _SUBREGION_COUNTRIES.items()
    for code in codes
}


def subregion_for_country(alpha_2: str) -> str:
    if not alpha_2:
        return ""
    return _SUBREGIONS_BY_ALPHA_2.get(alpha_2.upper(), "")
