from disaster_report.models import ReportPlace, SourceReport

def disease_from_title(title: str) -> str: ...
def derive_search_keys(
    report: SourceReport,
    *,
    disease: str = ...,
) -> tuple[str, str]: ...
def derive_repoll_keys(report: SourceReport) -> list[str]: ...
def place_token(place: ReportPlace) -> str: ...
