from disaster_report.models import ReportPlace

def format_title(*parts: str) -> str: ...
def normalise_subdivision(name: str) -> str: ...
def normalise_country(name: str) -> str: ...
def smallest_place(places: list[ReportPlace]) -> tuple[str, str]: ...
def format_place(smallest: str, country: str) -> str: ...
