class TestScanCountries:
    def test_drc_with_the_resolves_to_cd_not_cg(self) -> None: ...
    def test_drc_without_the_resolves_to_cd_not_cg(self) -> None: ...
    def test_drc_short_alias_resolves_to_cd(self) -> None: ...
    def test_congo_alone_resolves_to_cg(self) -> None: ...
    def test_south_georgia_does_not_match_georgia(self) -> None: ...
    def test_georgia_alone_matches_ge(self) -> None: ...
    def test_longest_first_drc_beats_congo_substring(self) -> None: ...
    def test_uninhabited_territories_dropped(self) -> None: ...
    def test_hong_kong_resolves_to_hk_not_cn(self) -> None: ...
    def test_dedupes_repeated_country(self) -> None: ...

class TestScanSubdivision:
    def test_kerala_resolves_under_india(self) -> None: ...
    def test_kinshasa_resolves_under_drc(self) -> None: ...
    def test_rwampara_resolves_under_uganda_not_sri_lanka(self) -> None: ...
    def test_rwampara_does_not_resolve_under_sri_lanka(self) -> None: ...
    def test_tristan_da_cunha_does_not_resolve_under_uk(self) -> None: ...
    def test_city_not_admin1_returns_empty(self) -> None: ...
    def test_case_insensitive_match(self) -> None: ...
    def test_no_subdivision_in_text_returns_empty(self) -> None: ...
    def test_unknown_country_returns_empty(self) -> None: ...

class TestExtractPlacesFromText:
    def test_global_title_short_circuits_to_empty(self) -> None: ...
    def test_global_case_insensitive(self) -> None: ...
    def test_multi_country_not_short_circuited(self) -> None: ...
    def test_places_carry_four_keys(self) -> None: ...
    def test_place_region_from_un_m49(self) -> None: ...
    def test_place_subdivision_resolved(self) -> None: ...
    def test_drc_not_canonicalized_to_cg(self) -> None: ...
    def test_locality_always_empty(self) -> None: ...
    def test_html_stripped_from_body(self) -> None: ...
