class TestFormatTitle:
    def test_joins_non_empty_parts_with_single_spaces(self) -> None: ...
    def test_skips_empty_parts(self) -> None: ...
    def test_returns_empty_when_all_parts_empty(self) -> None: ...
    def test_strips_whitespace_around_parts(self) -> None: ...


class TestNormaliseSubdivision:
    def test_strips_chinese_sheng_suffix(self) -> None: ...
    def test_strips_hong_kong_sar_suffix(self) -> None: ...
    def test_strips_guangxi_zhuangzu_zizhiqu_suffix(self) -> None: ...
    def test_strips_accents(self) -> None: ...
    def test_no_change_for_plain_name(self) -> None: ...
    def test_returns_empty_for_empty_input(self) -> None: ...
    def test_case_insensitive_suffix_match(self) -> None: ...


class TestNormaliseCountry:
    def test_dr_congo_alias(self) -> None: ...
    def test_uk_alias(self) -> None: ...
    def test_passes_through_short_form_unchanged(self) -> None: ...
    def test_returns_empty_for_empty_input(self) -> None: ...


class TestSmallestPlace:
    def test_locality_wins_over_subdivision(self) -> None: ...
    def test_subdivision_used_when_no_locality(self) -> None: ...
    def test_country_fallback_when_no_locality_or_subdivision(self) -> None: ...
    def test_returns_empty_pair_for_empty_places(self) -> None: ...
    def test_uses_first_place_only(self) -> None: ...
    def test_subdivision_normalised(self) -> None: ...
    def test_strips_locality_offset_when_present(self) -> None: ...


class TestFormatPlace:
    def test_smallest_with_country(self) -> None: ...
    def test_smallest_equals_country(self) -> None: ...
    def test_empty_smallest_keeps_country(self) -> None: ...
    def test_both_empty_returns_empty(self) -> None: ...
    def test_empty_country_keeps_smallest(self) -> None: ...
