class TestSettings:
    def test_loads_database_url_from_config(self, monkeypatch, tmp_path) -> None: ...
    def test_openrouter_key_from_secrets_file(self, monkeypatch, tmp_path) -> None: ...
    def test_openrouter_model_from_config(self, tmp_path) -> None: ...
    def test_empty_api_key_raises(self) -> None: ...
    def test_empty_model_raises(self) -> None: ...
    def test_settings_is_frozen_after_construction(self) -> None: ...
    def test_db_url_defaults_to_local_sqlite(self) -> None: ...
    def test_missing_secrets_file_raises_clear_error(
        self, monkeypatch, tmp_path
    ) -> None: ...
    def test_ai_key_is_never_logged(self, monkeypatch, tmp_path, caplog) -> None: ...
