from datetime import datetime

from disaster_report.models import (
    IncidentLog,
    NewsItem,
    ReportPlace,
    SourceReport,
)

FIXED_NOW: datetime
WINDOW: int

def _clock() -> datetime: ...
def _build_report(
    *,
    source: str = ...,
    source_id: str = ...,
    incident_type: str = ...,
    name: str = ...,
    places: list[ReportPlace] | None = ...,
    report_date: str = ...,
    raw_fields: dict[str, object] | None = ...,
) -> SourceReport: ...
def _build_news(
    *,
    url: str = ...,
    title: str = ...,
    body: str = ...,
    published_date: str = ...,
    source: str = ...,
    domain: str = ...,
    image: str = ...,
) -> NewsItem: ...
def _build_log(
    *,
    incident_id: str,
    log_date: str = ...,
    summary: str = ...,
) -> IncidentLog: ...
def _new_incident_id() -> str: ...

class TestReportIngest:
    def test_ingest_returns_deterministic_id_from_natural_key(self, tmp_path) -> None: ...
    def test_re_ingest_same_natural_key_is_idempotent(self, tmp_path) -> None: ...
    def test_two_sources_same_internal_id_stay_distinct(self, tmp_path) -> None: ...
    def test_report_file_lands_in_source_partition_staging(self, tmp_path) -> None: ...
    def test_read_source_report_keys_returns_colon_natural_keys(self, tmp_path) -> None: ...

class TestReportPlaces:
    def test_ingest_and_read_places(self, tmp_path) -> None: ...
    def test_duplicate_place_ingest_is_idempotent(self, tmp_path) -> None: ...
    def test_places_survive_report_move_to_incident(self, tmp_path) -> None: ...

class TestNewsIngest:
    def test_ingest_returns_deterministic_id_from_url(self, tmp_path) -> None: ...
    def test_re_ingest_same_url_is_idempotent(self, tmp_path) -> None: ...
    def test_news_file_lands_in_staging(self, tmp_path) -> None: ...

class TestNewsIncidentLink:
    def test_assign_moves_news_to_incident_dir(self, tmp_path) -> None: ...
    def test_read_incident_for_news(self, tmp_path) -> None: ...
    def test_reassign_pending_news_moves_between_incidents(self, tmp_path) -> None: ...
    def test_assign_refuses_summarized_news(self, tmp_path) -> None: ...

class TestReportIncidentLink:
    def test_link_moves_report_to_incident_dir(self, tmp_path) -> None: ...
    def test_link_auto_fills_search_keys_from_birthing_report(self, tmp_path) -> None: ...
    def test_second_link_does_not_overwrite_search_keys(self, tmp_path) -> None: ...
    def test_read_report_ids_for_incident(self, tmp_path) -> None: ...
    def test_read_incident_ids_for_report(self, tmp_path) -> None: ...

class TestTimeline:
    def test_append_creates_log_file(self, tmp_path) -> None: ...
    def test_same_day_upsert_merges_with_single_newline(self, tmp_path) -> None: ...
    def test_distinct_dates_admitted(self, tmp_path) -> None: ...
    def test_read_timeline_ordered_by_date_ascending(self, tmp_path) -> None: ...

class TestTimelineWithProvenance:
    def test_moves_news_into_log_dir(self, tmp_path) -> None: ...
    def test_read_summarized_news_ids(self, tmp_path) -> None: ...
    def test_read_logs_with_news_co_locates(self, tmp_path) -> None: ...
    def test_rerun_does_not_duplicate(self, tmp_path) -> None: ...

class TestReadIncidents:
    def test_genesis_is_earliest_report_by_date(self, tmp_path) -> None: ...
    def test_category_disease_for_who_source(self, tmp_path) -> None: ...
    def test_category_geophysical_for_usgs(self, tmp_path) -> None: ...
    def test_empty_store_returns_empty_list(self, tmp_path) -> None: ...

class TestActiveIncidents:
    def test_active_fires_on_pending_news_in_window(self, tmp_path) -> None: ...
    def test_active_ignores_old_pending_news(self, tmp_path) -> None: ...
    def test_active_ignores_summarized_news(self, tmp_path) -> None: ...

class TestMergeIncidents:
    def test_merge_moves_reports(self, tmp_path) -> None: ...
    def test_merge_moves_pending_news(self, tmp_path) -> None: ...
    def test_merge_moves_logs_and_summarized_news(self, tmp_path) -> None: ...
    def test_merge_same_date_logs_join_with_newline(self, tmp_path) -> None: ...
    def test_merge_keeps_target_search_keys(self, tmp_path) -> None: ...
    def test_merge_noop_on_missing_source(self, tmp_path) -> None: ...

class TestSetSearchKeys:
    def test_set_keys_writes_to_manifest(self, tmp_path) -> None: ...
    def test_set_keys_overwrites(self, tmp_path) -> None: ...

class TestPersistence:
    def test_reload_rebuilds_indexes_from_disk(self, tmp_path) -> None: ...

class TestResumabilityStamp:
    def test_mark_report_searched_makes_key_appear(self, tmp_path) -> None: ...
    def test_unsearched_report_absent(self, tmp_path) -> None: ...

class TestExtendedMonitoring:
    def _birth(self, store, tmp_path, *, source_id: str) -> str: ...
    def test_set_extended_monitoring_writes_flag(self, tmp_path) -> None: ...
    def test_extended_monitoring_incidents_returns_only_flagged(
        self, tmp_path
    ) -> None: ...
    def test_extended_monitoring_default_false_when_absent(
        self, tmp_path
    ) -> None: ...
    def test_repolllable_unions_active_and_extended(self, tmp_path) -> None: ...
    def test_set_extended_monitoring_noop_when_unchanged(
        self, tmp_path
    ) -> None: ...
