from disaster_report.models import NewsItem
from disaster_report.sources.ddg_news import DuckDuckGoNewsAdapter

FIXTURE: str
SEARCH_QUERY: str
ARTICLE_KEYS: tuple[str, ...]

class TestDuckDuckGoNewsAdapter:
    adapter: DuckDuckGoNewsAdapter

    def test_search_returns_news_items_from_fixture(self, monkeypatch) -> None: ...
    def test_each_news_item_carries_six_canonical_keys(self, monkeypatch) -> None: ...
    def test_region_pinned_to_worldwide_wt_wt(self, monkeypatch) -> None: ...
    def test_max_results_set_above_library_default(self, monkeypatch) -> None: ...
    def test_ddgs_exception_returns_empty_not_raises(self, monkeypatch) -> None: ...

def first_news_item(items: list[NewsItem]) -> NewsItem: ...
