from disaster_report.models import NewsItem
from disaster_report.sources.ddg_news import DuckDuckGoNewsAdapter

FIXTURE: str
SEARCH_QUERY: str
ARTICLE_KEYS: tuple[str, ...]

class TestDuckDuckGoNewsAdapter:
    adapter: DuckDuckGoNewsAdapter

    def test_search_returns_news_items_from_fixture(self, monkeypatch) -> None: ...
    def test_each_news_item_carries_six_canonical_keys(self, monkeypatch) -> None: ...
    def test_region_pinned_to_worldwide_wt_wt(self, monkeypatch) -> None: ...
    def test_max_results_set_above_library_default(self, monkeypatch) -> None: ...
    def test_ddgs_exception_returns_empty_not_raises(self, monkeypatch) -> None: ...

def first_news_item(items: list[NewsItem]) -> NewsItem: ...

class TestDeriveTitleFromSlug:
    def test_msn_article_url_extracts_slug(self) -> None: ...
    def test_msn_vi_suffix_url_extracts_slug(self) -> None: ...
    def test_non_msn_url_returns_empty(self) -> None: ...

class TestIsGenericTitle:
    def test_msn_is_generic(self) -> None: ...
    def test_client_challenge_is_generic(self) -> None: ...
    def test_empty_is_generic(self) -> None: ...
    def test_real_title_is_not_generic(self) -> None: ...
