from disaster_report.models import SourceReport
from disaster_report.sources.gdacs import GDACSAdapter

CASSETTE: str
ERROR_CASSETTE_SLUG: str

class TestGDACSAdapter:
    adapter: GDACSAdapter

    def test_fetch_returns_source_reports_from_rss_feed(self) -> None: ...
    def test_each_source_report_carries_gdacs_source_name(self) -> None: ...
    def test_incident_type_mapped_from_gdacs_eventtype_never_unknown(self) -> None: ...
    def test_source_report_name_matches_item_title(self) -> None: ...
    def test_report_date_is_iso_parseable(self) -> None: ...
    def test_raw_fields_preserve_alertlevel_eventtype_and_country(self) -> None: ...
    def test_population_read_via_value_attribute(self) -> None: ...
    def test_source_id_is_the_link_eventid(self) -> None: ...
    def test_should_monitor_filters_over_reporting(self) -> None: ...
    def test_derive_keys_returns_strict_and_loose_search_phrases(self) -> None: ...
    def test_derive_keys_empty_places_skips_strict(self) -> None: ...
    def test_fetch_raises_typed_error_on_soft_200(self) -> None: ...

class TestGDACSExtractCanonicalName:
    def test_earthquake_extracts_magnitude_from_numeric_severity(self) -> None: ...
    def test_earthquake_extracts_magnitude_from_severitytext_string(self) -> None: ...
    def test_tropical_cyclone_uses_eventname_when_present(self) -> None: ...
    def test_tropical_cyclone_parses_storm_name_from_title_when_eventname_empty(self) -> None: ...
    def test_volcano_extracts_name_from_title(self) -> None: ...
    def test_flood_omits_identifier(self) -> None: ...
    def test_forest_fire_omits_identifier(self) -> None: ...
    def test_drought_with_country(self) -> None: ...
    def test_drought_degenerate_no_place(self) -> None: ...
    def test_normalises_chinese_subdivision(self) -> None: ...

class TestGDACSDeriveRepollKeys:
    def test_with_places_delegates_to_shared_derive_repoll_keys(self) -> None: ...
    def test_empty_places_does_not_fabricate_country(self) -> None: ...

def first_source_report(reports: list[SourceReport]) -> SourceReport: ...
def build_gdacs_report(
    *,
    source: str = ...,
    source_id: str = ...,
    incident_type: str = ...,
    name: str = ...,
    places: list[dict[str, str]] | None = ...,
    report_date: str = ...,
    raw_fields: dict[str, object] | None = ...,
) -> SourceReport: ...
