class TestResolveRegion:
    def test_global_in_name_returns_global(self) -> None: ...
    def test_disease_without_global_in_name_returns_global(self) -> None: ...
    def test_drought_with_europe_in_summary_returns_europe(self) -> None: ...
    def test_non_disease_no_summary_no_global_returns_unknown(self) -> None: ...
    def test_disease_with_country_in_summary_returns_that_region(self) -> None: ...
