class TestResolveRegion:
    def test_global_in_name_returns_global(self) -> None: ...
    def test_disease_without_global_in_name_returns_global(self) -> None: ...
    def test_drought_with_europe_in_summary_returns_europe(self) -> None: ...
    def test_non_disease_no_summary_no_global_returns_unknown(self) -> None: ...
    def test_disease_with_country_in_summary_returns_that_region(self) -> None: ...


class TestResolveGdacsLink:
    def test_link_field_used_directly_when_present(self) -> None: ...
    def test_url_dict_report_subkey_used_when_no_link(self) -> None: ...
    def test_constructed_from_source_id_and_episodeid_for_degenerate_drought(self) -> None: ...
    def test_eventid_in_raw_fields_preferred_over_source_id(self) -> None: ...
    def test_returns_empty_when_nothing_reconstructable(self) -> None: ...


class TestGenerateMdReportDayPrimary:
    def test_day_primary_shows_3_most_recent_days(self) -> None: ...
    def test_each_incident_shows_only_that_day_log(self) -> None: ...
    def test_empty_days_skipped(self) -> None: ...
    def test_incidents_sorted_by_severity_within_day(self) -> None: ...
    def test_date_stripped_from_incident_heading(self) -> None: ...
    def test_new_badge_on_first_log_date(self) -> None: ...
    def test_region_subheadings_present(self) -> None: ...
    def test_section_header_says_recorded_on_this_date(self) -> None: ...
