class TestExtractUrl:
    def test_extracts_first_http_url(self) -> None: ...
    def test_returns_none_when_no_url(self) -> None: ...
    def test_strips_trailing_punctuation(self) -> None: ...


class TestSourceId:
    def test_is_16_hex_chars(self) -> None: ...
    def test_is_deterministic(self) -> None: ...


class TestProcessIssue:
    def test_rejects_when_body_has_no_url(self) -> None: ...
    def test_reimports_existing_manual_report_without_fetching(self) -> None: ...
    def test_rejects_when_fetch_returns_none(self) -> None: ...
    def test_rejects_when_classifier_says_not_disaster(self) -> None: ...
    def test_full_ingest_path_births_incident_and_links_news(self) -> None: ...
