from typing import Any

from disaster_report.ai.base import FilterResult
from disaster_report.models import IncidentLog, NewsItem

MODEL: str
INVALID_MODEL: str

def _stub_filter_cot(monkeypatch: Any, *, kept_urls: set[str]) -> None: ...
def _stub_summary_cot(monkeypatch: Any, *, summary: str, has_relevant_updates: bool = ...) -> None: ...
def _fake_filter_cot_call(candidates: Any, *, kept_urls: set[str]) -> Any: ...
def _fake_summary_cot_call(
    selected_news: Any, prior_summaries: Any, *, summary: str, has_relevant_updates: bool = ...
) -> Any: ...

class _FakeLM:
    def __init__(self, *, raise_error: Exception | None = None) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class _FakeFilterCOT:
    def __init__(
        self,
        *,
        kept_urls: set[str] | None = None,
        raise_error: Exception | None = None,
    ) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class _FakeSummaryCOT:
    def __init__(
        self,
        *,
        summary: str = ...,
        has_relevant_updates: bool = ...,
        raise_error: Exception | None = None,
    ) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class TestOpenRouterDigester:
    def test_filter_returns_result_from_canned_prediction(
        self, monkeypatch: Any
    ) -> None: ...
    def test_filter_takes_candidate_news_and_incident_context(self) -> None: ...
    def test_filter_takes_no_prior_summaries(self) -> None: ...
    def test_filter_result_carries_relevant_subset_of_news(
        self, monkeypatch: Any
    ) -> None: ...
    def test_filter_result_carries_per_item_relevance_score(
        self, monkeypatch: Any
    ) -> None: ...
    def test_filter_result_has_no_summary(self, monkeypatch: Any) -> None: ...
    def test_filter_filters_non_relevant_news(self, monkeypatch: Any) -> None: ...
    def test_filter_keeps_relevant_news_with_score_one(
        self, monkeypatch: Any
    ) -> None: ...
    def test_invalid_model_raises_bad_request_on_filter(
        self, monkeypatch: Any
    ) -> None: ...
    def test_summarize_returns_summary_from_canned_prediction(
        self, monkeypatch: Any
    ) -> None: ...
    def test_summarize_takes_selected_news_and_prior_summaries(self) -> None: ...
    def test_summarize_takes_incident_context(self) -> None: ...
    def test_summarize_passes_prior_summaries_to_cot(
        self, monkeypatch: Any
    ) -> None: ...
    def test_summarize_returns_non_empty_summary(self, monkeypatch: Any) -> None: ...
    def test_summarize_returns_summary_result(self, monkeypatch: Any) -> None: ...
    def test_summarize_has_relevant_updates_flag(self, monkeypatch: Any) -> None: ...
    def test_invalid_model_raises_bad_request_on_summarize(
        self, monkeypatch: Any
    ) -> None: ...

def build_candidate_news() -> list[NewsItem]: ...
def build_selected_news() -> list[NewsItem]: ...
def build_prior_timeline() -> list[IncidentLog]: ...
def load_filter_result(result: FilterResult) -> FilterResult: ...
