from pathlib import Path

from disaster_report.models import SourceReport


def _build_report(
    *,
    source: str = ...,
    source_id: str = ...,
    incident_type: str = ...,
    name: str = ...,
    country_code: str = ...,
    report_date: str = ...,
    raw_fields: dict | None = ...,
) -> SourceReport: ...


class TestNormalizeIncidentName:
    def test_strips_usgs_magnitude_prefix(self) -> None: ...
    def test_strips_magnitude_word_prefix(self) -> None: ...
    def test_keeps_name_without_prefix(self) -> None: ...
    def test_falls_back_when_strip_empties(self) -> None: ...


class TestParseUsgsIds:
    def test_parses_comma_separated(self) -> None: ...
    def test_returns_empty_for_none(self) -> None: ...
    def test_returns_empty_for_empty_string(self) -> None: ...


class TestFindExistingIncidentUsgsFamily:
    def test_usgs_event_id_family_matches(self, tmp_path: Path) -> None: ...
    def test_no_usgs_ids_returns_none_quickly(self, tmp_path: Path) -> None: ...


class TestFindExistingIncidentWindow:
    def test_matches_same_type_country_within_14d(self, tmp_path: Path) -> None: ...
    def test_rejects_different_country(self, tmp_path: Path) -> None: ...
    def test_rejects_outside_window(self, tmp_path: Path) -> None: ...
    def test_rejects_different_incident_type(self, tmp_path: Path) -> None: ...
