class TestEnrichNewsItems:
    def test_enriches_title_body_author_sitename_when_fetch_succeeds(self) -> None: ...
    def test_keeps_original_when_fetch_returns_none(self) -> None: ...
    def test_partial_enrichment_when_fetched_field_is_empty(self) -> None: ...
    def test_empty_list_passes_through(self) -> None: ...
