from pathlib import Path
from unittest.mock import MagicMock

import pytest
from disaster_report.models import SourceReport
from disaster_report.store.content import ContentStore


def _build_report(*, source_id: str = ...) -> SourceReport: ...
def _birth(store: ContentStore, tmp_path: Path, *, source_id: str) -> str: ...

class TestParseBody:
    def test_parses_incident_id_and_action(self) -> None: ...
    def test_returns_none_when_heading_absent(self) -> None: ...
    def test_returns_none_for_empty_body(self) -> None: ...

class TestResolveIncident:
    def test_full_uuid_exact_match(self, tmp_path: Path) -> None: ...
    def test_eight_char_prefix_unique(self, tmp_path: Path) -> None: ...
    def test_ambiguous_prefix_returns_none(self, tmp_path: Path) -> None: ...
    def test_no_match_returns_none(self, tmp_path: Path) -> None: ...
    def test_non_hex_returns_none(self, tmp_path: Path) -> None: ...

class TestProcessIssue:
    def _patch_common(self, monkeypatch: pytest.MonkeyPatch) -> dict[str, MagicMock]: ...
    def test_applies_enable_action(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None: ...
    def test_applies_disable_action(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None: ...
    def test_rejects_when_incident_id_missing(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None: ...
    def test_rejects_when_action_unrecognized(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None: ...
    def test_rejects_when_identifier_does_not_resolve(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None: ...
