from collections.abc import Callable
from datetime import datetime

from disaster_report.reporting.markdown import MarkdownRenderer
from disaster_report.reporting.report import ReportDocument
from disaster_report.store.base import Warehouse

GEOPHYSICAL_INCIDENT_ID: int
DISEASE_INCIDENT_ID: int
UNESCAPED_AI_SUMMARY: str
GEOPHYSICAL_TIMELINE_SUMMARY: str

class TestReportDocument:
    def test_build_report_surfaces_incidents_from_read_model(
        self, db_url, clock
    ) -> None: ...
    def test_build_report_surfaces_timeline_from_read_model(
        self, db_url, clock
    ) -> None: ...
    def test_build_report_surfaces_news_from_read_model(
        self, db_url, clock
    ) -> None: ...
    def test_report_document_is_json_serialisable(self, db_url, clock) -> None: ...

class TestMarkdownRenderer:
    renderer: MarkdownRenderer

    def test_renders_over_report_document(self, db_url, clock) -> None: ...
    def test_splits_geophysical_and_disease_parts(self, db_url, clock) -> None: ...
    def test_renders_type_subsections_under_categories(self) -> None: ...
    def test_disease_incident_with_real_who_id_routes_to_disease_not_geophysical(
        self, db_url, clock
    ) -> None: ...
    def test_escapes_unconstrained_ai_summary_text(self, db_url, clock) -> None: ...
    def test_render_surfaces_read_model_timeline(self, db_url, clock) -> None: ...
    def test_render_path_has_no_ai_dependency(self) -> None: ...

def build_populated_warehouse(db_url: str) -> Warehouse: ...
def build_report_document(
    db_url: str, clock: Callable[[], datetime]
) -> ReportDocument: ...
