from disaster_report.models import (
    Incident,
    IncidentLog,
    NewsItem,
    ReportPlace,
    SourceReport,
)
from disaster_report.store.base import Warehouse

ACTIVE_WINDOW_DAYS: int

class TestSourceReportIngest:
    def test_ingest_new_source_report_persists_record_with_report_id(
        self, db_url
    ) -> None: ...
    def test_re_ingest_same_source_and_source_id_is_idempotent(
        self, db_url
    ) -> None: ...
    def test_each_source_keeps_own_raw_schema_in_raw_fields(self, db_url) -> None: ...
    def test_two_sources_same_internal_id_stay_distinct(self, db_url) -> None: ...
    def test_source_report_has_no_places_json_column(self, db_url) -> None: ...

class TestReportPlaces:
    def test_ingest_report_places_persists_one_row_per_place(self, db_url) -> None: ...
    def test_report_with_multiple_countries_has_multiple_place_rows(
        self, db_url
    ) -> None: ...
    def test_read_report_places_returns_all_rows_for_report(self, db_url) -> None: ...
    def test_ocean_report_has_empty_country_code(self, db_url) -> None: ...
    def test_duplicate_place_row_is_idempotent(self, db_url) -> None: ...

class TestNewsItemIngest:
    def test_ingest_new_news_item_persists_record_with_news_id(
        self, db_url
    ) -> None: ...
    def test_re_ingest_same_url_is_idempotent(self, db_url) -> None: ...
    def test_published_date_is_sticky_on_re_ingest(self, db_url) -> None: ...

class TestReportIncidents:
    def test_insert_report_incident_persists_membership(self, db_url) -> None: ...
    def test_report_in_multiple_incidents_has_multiple_rows(self, db_url) -> None: ...
    def test_duplicate_report_incident_is_idempotent(self, db_url) -> None: ...

class TestNewsIncidents:
    def test_birth_new_news_assigns_new_incident_id(self, db_url) -> None: ...
    def test_join_existing_news_keeps_existing_incident_id(self, db_url) -> None: ...
    def test_news_incident_pk_enforces_one_incident_per_news(self, db_url) -> None: ...
    def test_read_incidents_for_news_returns_mapping(self, db_url) -> None: ...
    def test_read_incidents_for_news_empty_for_unknown_news(self, db_url) -> None: ...

class TestTimeline:
    def test_append_row_keyed_by_incident_id_and_log_datetime(self, db_url) -> None: ...
    def test_multiple_logs_same_incident_distinct_datetimes_admitted(
        self, db_url
    ) -> None: ...

class TestReadModel:
    def test_read_incidents_returns_view_derived_incidents(self, db_url) -> None: ...
    def test_read_incidents_genesis_is_earliest_by_date_report(
        self, db_url
    ) -> None: ...
    def test_read_incidents_category_derived_from_source(self, db_url) -> None: ...
    def test_read_timeline_returns_story_for_incident(self, db_url) -> None: ...
    def test_read_news_returns_items_for_incident_via_news_incidents(
        self, db_url
    ) -> None: ...

class TestResumabilityStamp:
    def test_mark_report_searched_adds_key_to_searched_set(self, db_url) -> None: ...
    def test_unmarked_report_absent_from_searched_set(self, db_url) -> None: ...
    def test_stamp_persisted_in_raw_fields_news_searched_at(self, db_url) -> None: ...
    def test_re_marking_report_searched_is_idempotent(self, db_url) -> None: ...

class TestNoChurn:
    def test_incident_view_has_no_stored_mutable_recency_field(
        self, db_url
    ) -> None: ...

class TestActiveIncidents:
    def test_active_incidents_derived_from_publication_date_within_window(
        self, db_url, clock
    ) -> None: ...
    def test_incident_with_only_old_publication_date_is_not_active(
        self, db_url, clock
    ) -> None: ...

class TestIncidentLogNews:
    def test_read_summarized_news_ids_empty_for_incident_with_no_logs(
        self, db_url
    ) -> None: ...
    def test_read_summarized_news_ids_returns_linked_ids_after_provenance_write(
        self, db_url
    ) -> None: ...
    def test_read_summarized_news_ids_grows_as_new_logs_with_new_news_added(
        self, db_url
    ) -> None: ...
    def test_read_summarized_news_ids_scoped_per_incident(self, db_url) -> None: ...
    def test_append_timeline_with_provenance_writes_log_row_and_junction_rows(
        self, db_url
    ) -> None: ...
    def test_append_timeline_with_provenance_junction_links_exactly_given_news_ids(
        self, db_url
    ) -> None: ...
    def test_append_timeline_with_provenance_is_idempotent_on_log_pk_collision(
        self, db_url
    ) -> None: ...
    def test_append_timeline_with_provenance_rolls_back_on_junction_fk_failure(
        self, db_url
    ) -> None: ...
    def test_append_timeline_with_provenance_parallel_to_append_timeline(
        self, db_url
    ) -> None: ...

class TestIncidentLogNewsBackfill:
    def test_backfill_links_existing_logs_to_news_published_before_log_datetime(
        self, db_url
    ) -> None: ...
    def test_backfill_does_not_link_news_published_after_log_datetime(
        self, db_url
    ) -> None: ...
    def test_backfill_is_idempotent_under_rerun(self, db_url) -> None: ...

def build_source_report(
    *,
    source: str = ...,
    source_id: str = ...,
    incident_type: str = ...,
    name: str = ...,
    places: list[ReportPlace] | None = ...,
    report_date: str = ...,
    raw_fields: dict[str, object] | None = ...,
) -> SourceReport: ...
def build_news_item(
    *,
    url: str = ...,
    title: str = ...,
    body: str = ...,
    published_date: str = ...,
    source: str = ...,
    domain: str = ...,
    image: str = ...,
) -> NewsItem: ...
def build_timeline_row(
    *,
    incident_id: int = ...,
    log_datetime: str = ...,
    summary: str = ...,
) -> IncidentLog: ...
def warehouse_with(warehouse: Warehouse, *rows: object) -> Warehouse: ...
def first_incident(incidents: list[Incident]) -> Incident: ...
