from disaster_report.models import SourceReport
from disaster_report.sources.usgs import USGSAdapter

CASSETTE: str
ERROR_CASSETTE_SLUG: str
SOFT_404_BODY: str

class TestUSGSAdapter:
    adapter: USGSAdapter

    def test_fetch_returns_source_reports_from_summary_feed(self) -> None: ...
    def test_each_source_report_carries_usgs_source_name(self) -> None: ...
    def test_each_source_report_is_typed_earthquake(self) -> None: ...
    def test_source_report_name_matches_feature_title(self) -> None: ...
    def test_report_date_is_iso_parseable(self) -> None: ...
    def test_raw_fields_preserve_magnitude_place_and_depth(self) -> None: ...
    def test_each_source_report_carries_standardized_places(self) -> None: ...
    def test_source_id_is_the_usgs_eventid(self) -> None: ...
    def test_should_monitor_keeps_significant_events(self) -> None: ...
    def test_derive_keys_returns_strict_and_loose_search_phrases(self) -> None: ...
    def test_derive_keys_empty_locality_degrades_to_country_only(self) -> None: ...
    def test_derive_keys_offshore_no_places_skips_strict(self) -> None: ...
    def test_fetch_raises_typed_error_on_soft_404(self) -> None: ...

class TestUSGSExtractCanonicalName:
    def test_usgs_earthquake_with_magnitude_and_locality(self) -> None: ...
    def test_usgs_earthquake_missing_magnitude(self) -> None: ...
    def test_usgs_earthquake_no_places(self) -> None: ...
    def test_usgs_earthquake_offshore_locality(self) -> None: ...
    def test_usgs_earthquake_normalises_subdivision_when_no_locality(self) -> None: ...

def first_source_report(reports: list[SourceReport]) -> SourceReport: ...
def build_kept_report(
    *,
    source: str = ...,
    source_id: str = ...,
    incident_type: str = ...,
    name: str = ...,
    places: list[dict[str, str]] | None = ...,
    report_date: str = ...,
    raw_fields: dict[str, object] | None = ...,
) -> SourceReport: ...
