from disaster_report.models import SourceReport
from disaster_report.sources.who import WHODiseaseOutbreakAdapter

CASSETTE: str
ERROR_CASSETTE_ORDERBY: str

class TestWHODiseaseOutbreakAdapter:
    adapter: WHODiseaseOutbreakAdapter

    def test_fetch_returns_source_reports_from_odata_feed(self) -> None: ...
    def test_each_source_report_carries_who_source_name(self) -> None: ...
    def test_each_source_report_carries_specific_disease_type(self) -> None: ...
    def test_title_respects_use_override_title_flag(self) -> None: ...
    def test_disease_name_extracted_from_title(self) -> None: ...
    def test_disease_name_extracted_from_title_handles_en_dash(self) -> None: ...
    def test_disease_name_split_on_dash_suffix(self) -> None: ...
    def test_report_date_is_iso_parseable(self) -> None: ...
    def test_raw_fields_preserve_guid_identity(self) -> None: ...
    def test_derive_keys_include_disease_name(self) -> None: ...
    def test_derive_keys_drops_disease_kwarg(self) -> None: ...
    def test_derive_keys_multi_country_skips_strict_disease_in_loose(self) -> None: ...
    def test_derive_keys_global_zero_places_skips_strict(self) -> None: ...
    def test_fetch_raises_on_clean_400_error_path(self) -> None: ...

class TestWHOExtractCanonicalName:
    def test_disease_with_country_only(self) -> None: ...
    def test_disease_global_no_places_uses_Global(self) -> None: ...
    def test_disease_uses_subdivision_when_available(self) -> None: ...
    def test_disease_normalises_messy_incident_type(self) -> None: ...
    def test_disease_unknown_falls_back_to_first_word(self) -> None: ...
    def test_disease_normalises_long_country_name(self) -> None: ...
    def test_title_suffix_country_overrides_body_scan_places(self) -> None: ...
    def test_title_global_suffix_overrides_places(self) -> None: ...
    def test_title_country_match_uses_subdivision_when_available(self) -> None: ...
    def test_title_without_suffix_falls_back_to_places(self) -> None: ...

class TestWHODeriveRepollKeys:
    def test_title_suffix_country_overrides_body_scan_places(self) -> None: ...
    def test_global_title_suffix_yields_countryless_keys(self) -> None: ...
    def test_title_without_suffix_falls_back_to_scan_countries(self) -> None: ...
    def test_no_title_no_country_yields_countryless_keys(self) -> None: ...

def first_source_report(reports: list[SourceReport]) -> SourceReport: ...
def build_who_report(
    *,
    source: str = ...,
    source_id: str = ...,
    incident_type: str | None = None,
    name: str = ...,
    places: list[dict[str, str]] | None = ...,
    report_date: str = ...,
    raw_fields: dict[str, object] | None = ...,
) -> SourceReport: ...
