from collections.abc import Callable
from datetime import datetime
from typing import Any

from disaster_report.models import (
    Incident,
    IncidentLog,
    NewsItem,
    ReportPlace,
    SourceReport,
)

class Warehouse:
    _engine: Any
    def __init__(
        self,
        db_url: str,
        *,
        clock: Callable[[], datetime] | None = None,
    ) -> None: ...
    def ingest_source_report(self, report: SourceReport) -> int: ...
    def ingest_report_places(
        self, report_id: int, places: list[ReportPlace]
    ) -> None: ...
    def read_report_places(self, report_id: int) -> list[ReportPlace]: ...
    def read_searched_report_keys(self) -> set[str]: ...
    def read_source_report_keys(self) -> set[str]: ...
    def mark_report_searched(
        self, source: str, source_id: str, timestamp: str
    ) -> None: ...
    def ingest_news_item(self, item: NewsItem) -> int: ...
    def read_news_item(self, news_id: int) -> NewsItem: ...
    def assign_news_to_incident(self, news_id: int, incident_id: int) -> None: ...
    def read_incident_for_news(self, news_id: int) -> int | None: ...
    def read_incidents_for_news(self, news_ids: set[int]) -> dict[int, set[int]]: ...
    def add_report_incident(self, report_id: int, incident_id: int) -> None: ...
    def read_report_ids_for_incident(self, incident_id: int) -> list[int]: ...
    def read_incident_ids_for_report(self, report_id: int) -> list[int]: ...
    def read_incident_ids_for_source_id(self, source_id: str) -> list[int]: ...
    def append_timeline(self, row: IncidentLog) -> None: ...
    def append_timeline_with_provenance(
        self, log: IncidentLog, news_ids: set[int]
    ) -> None: ...
    def read_summarized_news_ids(self, incident_id: int) -> set[int]: ...
    def read_source_reports(self) -> list[SourceReport]: ...
    def read_source_report_by_id(self, report_id: int) -> SourceReport | None: ...
    def read_timeline(self, incident_id: int) -> list[IncidentLog]: ...
    def read_incidents(self) -> list[Incident]: ...
    def read_news(self, incident_id: int) -> list[NewsItem]: ...
    def active_incidents(self, window_days: int) -> list[Incident]: ...
