from collections.abc import Callable
from datetime import datetime
from pathlib import Path

from disaster_report.models import (
    Incident,
    IncidentLog,
    NewsItem,
    ReportPlace,
    SourceReport,
)

class ContentStore:
    def __init__(
        self,
        tree_root: str | Path,
        *,
        clock: Callable[[], datetime] | None = None,
    ) -> None: ...
    def ingest_source_report(self, report: SourceReport) -> str: ...
    def ingest_report_places(
        self, report_id: str, places: list[ReportPlace]
    ) -> None: ...
    def read_report_places(self, report_id: str) -> list[ReportPlace]: ...
    def read_searched_report_keys(self) -> set[str]: ...
    def read_source_report_keys(self) -> set[str]: ...
    def mark_report_searched(
        self, source: str, source_id: str, timestamp: str
    ) -> None: ...
    def ingest_news_item(self, item: NewsItem) -> str: ...
    def read_news_item(self, news_id: str) -> NewsItem: ...
    def assign_news_to_incident(self, news_id: str, incident_id: str) -> None: ...
    def read_incident_for_news(self, news_id: str) -> str | None: ...
    def read_incidents_for_news(
        self, news_ids: set[str]
    ) -> dict[str, set[str]]: ...
    def add_report_incident(self, report_id: str, incident_id: str) -> None: ...
    def read_report_ids_for_incident(self, incident_id: str) -> list[str]: ...
    def read_incident_ids_for_report(self, report_id: str) -> list[str]: ...
    def read_incident_ids_for_source_id(self, source_id: str) -> list[str]: ...
    def append_timeline(self, row: IncidentLog) -> None: ...
    def append_timeline_with_provenance(
        self, log: IncidentLog, news_ids: set[str]
    ) -> None: ...
    def read_summarized_news_ids(self, incident_id: str) -> set[str]: ...
    def read_source_reports(self) -> list[SourceReport]: ...
    def read_source_report_by_id(self, report_id: str) -> SourceReport | None: ...
    def read_timeline(self, incident_id: str) -> list[IncidentLog]: ...
    def read_incidents(self) -> list[Incident]: ...
    def read_news(self, incident_id: str) -> list[NewsItem]: ...
    def active_incidents(self, window_days: int) -> list[Incident]: ...
    def extended_monitoring_incidents(self) -> list[Incident]: ...
    def repolllable_incidents(self, window_days: int) -> list[Incident]: ...
    def read_logs_with_news(
        self, incident_id: str
    ) -> list[tuple[IncidentLog, list[NewsItem]]]: ...
    def read_incident_search_keys(self, incident_id: str) -> list[str]: ...
    def set_search_keys(self, incident_id: str, search_keys: list[str]) -> None: ...
    def set_extended_monitoring(
        self, incident_id: str, enabled: bool
    ) -> None: ...
    def merge_incidents(self, source: str, target: str) -> None: ...
