from disaster_report.models import SourceReport

class WHODiseaseOutbreakAdapter:
    def __init__(self, orderby: str = ...) -> None: ...
    def fetch(self) -> list[SourceReport]: ...
    def derive_keys(self, report: SourceReport) -> tuple[str, str]: ...
