from typing import Any


def local_tag(tag: str) -> str: ...
def to_iso_date(rfc822: str) -> str: ...
def clean_html(raw: str) -> str: ...
def as_dict(obj: Any) -> dict[str, Any]: ...
def safe_float(value: object) -> float | None: ...
