from disaster_report.models import NewsItem

class DuckDuckGoNewsAdapter:
    def __init__(self) -> None: ...
    def search(self, query: str, timelimit: str | None = None) -> list[NewsItem]: ...

def _resolve_date(raw_date: str, url: str) -> str: ...
