from disaster_report.models import ReportPlace, SourceReport
import logging

logger: logging.Logger

class ERCCAdapter:
    source: str
    def __init__(
        self,
        path: str = ...,
    ) -> None: ...
    def fetch(self) -> list[SourceReport]: ...
    def derive_keys(self, report: SourceReport) -> tuple[str, str]: ...
    def derive_repoll_keys(self, report: SourceReport) -> list[str]: ...

def _item_to_report(item: object) -> SourceReport: ...
def _extract_canonical_name(
    raw_fields: dict[str, object],
    places: list[ReportPlace],
    report_date: str,
    incident_type: str,
) -> str: ...
def _resolve_incident_type(event_types_raw: str) -> str: ...
def _extract_places(
    main_country: str, countries_iso3: str
) -> list[ReportPlace]: ...
