from disaster_report.models import ReportPlace, SourceReport
import logging

logger: logging.Logger

class ERCCAdapter:
    source: str
    def __init__(
        self,
        path: str = ...,
    ) -> None: ...
    def fetch(self) -> list[SourceReport]: ...
    def derive_keys(self, report: SourceReport) -> tuple[str, str]: ...
    def derive_repoll_keys(self, report: SourceReport) -> list[str]: ...
    def build_source_link(
        self, raw_fields: dict[str, object], name: str
    ) -> dict[str, str]: ...
    def extract_physical(self, raw_fields: dict[str, object]) -> dict[str, object]: ...
    def find_existing_incident(
        self, wh: object, report: SourceReport, active_window_days: int = ...
    ) -> str | None: ...

def _item_to_report(item: object) -> SourceReport: ...
def _extract_canonical_name(
    raw_fields: dict[str, object],
    places: list[ReportPlace],
    report_date: str,
    incident_type: str,
) -> str: ...
def _resolve_incident_type(event_types_raw: str) -> str: ...
def _extract_places(
    main_country: str, countries_iso3: str
) -> list[ReportPlace]: ...
