from disaster_report.models import ReportPlace, SourceReport

class WHODiseaseOutbreakAdapter:
    source: str
    def __init__(self, orderby: str = ...) -> None: ...
    def fetch(self) -> list[SourceReport]: ...
    def derive_keys(self, report: SourceReport) -> tuple[str, str]: ...
    def derive_repoll_keys(self, report: SourceReport) -> list[str]: ...

def _extract_canonical_name(
    raw_fields: dict[str, object],
    places: list[ReportPlace],
    report_date: str,
    incident_type: str,
) -> str: ...
