def test_last_updated_set_at_creation():
    ...

def test_last_updated_reset_on_new_data():
    ...

def test_last_updated_unchanged_when_no_new_fingerprints():
    ...

def test_active_status_within_seven_day_boundary():
    ...

def test_stale_status_beyond_seven_day_boundary():
    ...

def test_unparseable_source_date_falls_back():
    ...

